### ISSUE TITLE
Information about digits

### ISSUE THREAD

**Issue by Rainer-Lang** [AleBarreto/SimpleLoginLibrary#2]
I had to open a new issue because the other issue is locked.

Here are the information you wanted:
https://fabric.io/kits/android/digits/summary
https://docs.fabric.io/android/digits/digits.html

**Comment by AleBarreto** [comment]
Interesting, I will search about. 
I think about adding (Instagram Login) and (Twitter Login) at the moment.

**Comment by Rainer-Lang** [comment]
digits is from Twitter :)
Nice project!

**Comment by prawins** [comment]
Error:(26, 13) Failed to resolve: com.github.AleBarreto:SimpleLoginLibrary:-SNAPSHOT

**Comment by AleBarreto** [comment]
You added this ? 

```
//Add it in your root build.gradle at the end of repositories:
allprojects {
    repositories {
        ...
        maven { url "https://jitpack.io" }
    }
}
```

choose Build -> Clean Project

**Comment by GopiKrishnaBandaru** [comment]
Getting Error:(26, 13) Failed to resolve: com.github.AleBarreto:SimpleLoginLibrary:-SNAPSHOT even though I added 

```
allprojects  {
     repositories {
         jcenter()
         maven { url "https://jitpack.io" }
     }
}
```

in build.gradle
