### ISSUE TITLE
Getting login status and get token 

### ISSUE THREAD

**Issue by konigsoft** [AleBarreto/SimpleLoginLibrary#5]
Hi @AleBarreto ,
have you plan to add a way to get the login status et get the current token. ?

looking forward to hearing from you.

**Comment by AleBarreto** [comment]
My intention was to obtain data that I consider important in the login ( name, email , photo, id) , but I can add what you asked

**Comment by konigsoft** [comment]
yes sure i understand
my request here is that you dont need to display the login button if the user is already logged in

---update---
done just modify the file can deal now with user logged status
